services:
  - type: web
    name: arness-community
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - server.js
        - index.html
        - css/**
        - js/** 