services:
  # Backend Service (API)
  - type: web
    name: pixel-ai-backend
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildFilter:
      paths:
        - "backend/**"
        - "start.sh"
        - "requirements.txt"
    buildCommand: "pip install -r requirements.txt && python -m backend.initialise"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
      - fromGroup: pixel-ai-secrets
      - key: SECRET_KEY
        generateValue: true
      # Эти переменные нужно задать вручную в дашборде Render для сервиса 'backend'
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_REDIRECT_URI
        sync: false # Сюда нужно вставить URL вашего фронтенда
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPERADMIN_USERNAMES
        sync: false
      - key: BACKEND_URL
        value: https://back-guqa.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: pixel-ai-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: frontend
          property: url

  # Frontend Service (React App)
  - type: web
    name: frontend
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: frontend
    buildFilter:
      paths:
      - "frontend/**"
    buildCommand: "npm install && npm install -g serve && npm run build"
    startCommand: "serve -s build"
    envVars:
      - fromGroup: pixel-ai-secrets

databases:
  - name: pixel-ai-db
    databaseName: pixel_ai_db
    user: pixel_ai_user 
